ci: add sonar to pr

diff --git a/.github/workflows/pr.yml b/.github/workflows/pr.yml
--- a/.github/workflows/pr.yml
+++ b/.github/workflows/pr.yml
@@ -1,8 +1,6 @@
 on:
-  workflow_dispatch:
-  # Enable this when the `pr-simple` workflow is not enough anymore
-  # pull_request:
-  #   types: [opened, synchronize, reopened]
+  pull_request:
+    types: [opened, synchronize, reopened]
 
 # cancel previous runs on the same PR
 concurrency:
@@ -20,6 +18,30 @@ defaults:
     shell: bash
 
 jobs:
+  build-lint:
+    name: 🚀 Build and Lint
+    runs-on: ubuntu-latest
+    timeout-minutes: 30
+    steps:
+      - uses: actions/checkout@v3
+        with:
+          ref: ${{ github.event.pull_request.head.sha }}
+          # We need to fetch all branches and commits so that Nx affected has a base to compare against.
+          fetch-depth: 0
+      - uses: nrwl/nx-set-shas@v3
+      - name: Install & cache node dependencies
+        uses: ./.github/actions/install-node-deps
+      - name: Package and cache builds
+        uses: ./.github/actions/package
+      - name: '🧪 Test linter'
+        run: pnpm nx affected --target=test-linter --parallel=2
+      - name: '🧪 Test type'
+        run: pnpm nx affected --target=test-type --parallel=2
+      - name: '🧪 Test unit'
+        run: pnpm nx affected --target=test-unit --parallel=2
+      - name: '🧪 Test circular'
+        run: pnpm nx affected --target=test-circular --parallel=2
+
   build:
     name: 🏗 Build Project
     runs-on: ubuntu-latest
@@ -41,8 +63,8 @@ jobs:
         id: get-project-changes
         uses: ./.github/actions/get-project-changes
 
-  app-lint-and-tests:
-    name: 🏛 App Tests
+  app-unit-tests-and-sonar:
+    name: 🏛 ${{ matrix.AFFECTED_APP }} - App Unit Tests and Sonar
     needs: build
     runs-on: ubuntu-latest
     if: join(fromJson(needs.build.outputs.affected_apps)) != ''
@@ -55,13 +77,17 @@ jobs:
       - uses: actions/checkout@v3
         with:
           ref: ${{ github.event.pull_request.head.sha }}
-      - name: Run tests
-        uses: ./.github/actions/lint-and-tests
+          # We need to fetch all branches and commits so that Nx affected has a base to compare against.
+          fetch-depth: 0
+      - name: Run unit tests and sonar
+        uses: ./.github/actions/unit-tests-and-sonar
         with:
           path: ${{ matrix.AFFECTED_APP }}
+          github_token: ${{ secrets.GITHUB_TOKEN }}
+          sonar_token: ${{ secrets.SONAR_TOKEN }}
 
-  library-lint-and-tests:
-    name: 📚 Library Tests
+  library-unit-tests-and-sonar:
+    name: 📚 ${{ matrix.AFFECTED_LIB }} - Library Unit Tests and Sonar
     needs: build
     runs-on: ubuntu-latest
     if: join(fromJson(needs.build.outputs.affected_libs)) != ''
@@ -74,17 +100,33 @@ jobs:
       - uses: actions/checkout@v3
         with:
           ref: ${{ github.event.pull_request.head.sha }}
-      - name: Run tests
-        uses: ./.github/actions/lint-and-tests
+          # We need to fetch all branches and commits so that Nx affected has a base to compare against.
+          fetch-depth: 0
+      - name: Run unit tests and sonar
+        uses: ./.github/actions/unit-tests-and-sonar
         with:
           path: ${{ matrix.AFFECTED_LIB }}
+          github_token: ${{ secrets.GITHUB_TOKEN }}
+          sonar_token: ${{ secrets.SONAR_TOKEN }}
 
   validate-pr:
     name: ✅ Validate the PR
     runs-on: ubuntu-latest
     if: ${{ always() }}
-    needs: [build, library-lint-and-tests, app-lint-and-tests]
+    needs:
+      [
+        build-lint,
+        build,
+        library-unit-tests-and-sonar,
+        app-unit-tests-and-sonar,
+      ]
     steps:
+      - name: Validate build-lint
+        run: |
+          if [[ ${{ needs.build-lint.result }} = "failure" ]]; then
+            echo "build-lint failed"
+            exit 1
+          fi
       - name: Validate build
         run: |
           if [[ ${{ needs.build.result }} = "failure" ]]; then
@@ -93,13 +135,13 @@ jobs:
           fi
       - name: Validate app tests
         run: |
-          if [[ ${{ needs.app-lint-and-tests.result }} = "failure" ]]; then
+          if [[ ${{ needs.app-unit-tests-and-sonar.result }} = "failure" ]]; then
             echo "App tests failed"
             exit 1
           fi
       - name: Validate library tests
         run: |
-          if [[ ${{ needs.library-lint-and-tests.result }} = "failure" ]]; then
+          if [[ ${{ needs.library-unit-tests-and-sonar.result }} = "failure" ]]; then
             echo "Library tests failed"
             exit 1
           fi
